// games.js — 游戏板块元数据（静态模板阶段：展示设计，非交互）
// 记忆设计原则：多感官（听+看+动）、短时高频、即时反馈、闯关激励

export const GAMES = [
  {
    id: 'listen_find',
    name: '听音找图',
    emoji: '🎧',
    tagline: '听一听，点一点，找到它！',
    difficulty: 1,
    stars: '★',
    memory: '听力入门 · 词图匹配',
    scene: '客厅 / 睡前',
    time: '3 分钟',
    kp: '任意单元词汇（如 U3 课堂指令）',
    howto: [
      '播放一个单词的音频（或家长念一遍）',
      '屏幕上出现 4 张图片',
      '孩子点选听到的图片',
      '点对→欢呼声+星星，点错→鼓励重听',
    ],
    tips: '第一次玩先让孩子看着图片听 2 遍，再进入答题，降低挫败感。',
    sketch: 'listen_find',
  },
  {
    id: 'memory',
    name: '翻牌配对',
    emoji: '🃏',
    tagline: '翻开两张，单词和图配成对！',
    difficulty: 2,
    stars: '★★',
    memory: '词图记忆 · 专注力',
    scene: '书桌 / 周末',
    time: '5 分钟',
    kp: '词汇（如 U2 文具、U4 学校用品）',
    howto: [
      '8~12 张牌面朝下，一半是单词、一半是图片',
      '每次翻开两张：单词和对应图片配成一对',
      '配对成功牌消失，配对失败盖回去',
      '全部配对完成通关',
    ],
    tips: '牌少一点（8 张）起步，孩子熟悉后再加牌。',
    sketch: 'memory',
  },
  {
    id: 'fishing',
    name: '单词钓鱼',
    emoji: '🎣',
    tagline: '听到哪个词，就钓哪条鱼！',
    difficulty: 2,
    stars: '★★',
    memory: '听力 + 认读',
    scene: '客厅',
    time: '3 分钟',
    kp: '词汇（如 U1 问候词、U4 学校用品）',
    howto: [
      '池塘里游着几条写着单词的鱼',
      '播放单词音频，鱼身上的字也在变大（提示）',
      '孩子点/拍对应的鱼，钓竿放下',
      '钓对→鱼跳起来+音效，全部钓完通关',
    ],
    tips: '鱼身上的字会随音频同步放大，帮还不认字的孩子建立音→形连接。',
    sketch: 'fishing',
  },
  {
    id: 'whack',
    name: '打地鼠',
    emoji: '🔨',
    tagline: '听到单词，敲中它！',
    difficulty: 3,
    stars: '★★★',
    memory: '听力反应 + 认读',
    scene: '客厅 / 运动型玩法',
    time: '2 分钟',
    kp: '词汇（如 U5 家人、U3 课堂指令）',
    howto: [
      '3×3 地鼠洞里，地鼠轮流冒头，每只头顶顶着一个单词',
      '播放目标单词音频',
      '孩子在 3 秒内敲中对应地鼠',
      '敲中加星，敲错换下一只',
    ],
    tips: '节奏游戏，孩子容易嗨，一次 2 分钟就够，注意别玩到兴奋过度。',
    sketch: 'whack',
  },
  {
    id: 'letters',
    name: '字母拼拼乐',
    emoji: '🧩',
    tagline: '看图片，用字母块拼出单词！',
    difficulty: 3,
    stars: '★★★',
    memory: '拼写启蒙（适合二上数字/颜色）',
    scene: '书桌',
    time: '5 分钟',
    kp: '词汇（如二上 one-ten、颜色词）',
    howto: [
      '屏幕上方显示一张图片（如 3 个苹果）',
      '下方给出打乱的字母块',
      '孩子把字母块拖到槽里拼成单词（three）',
      '拼对→图片变彩色+发音，拼错→字母块抖动提示',
    ],
    tips: '一年级以认读为主，拼写到二年级数字/颜色单元再开放，防止过早挫败。',
    sketch: 'letters',
  },
  {
    id: 'bingo',
    name: '单词 Bingo',
    emoji: '🎯',
    tagline: '听单词盖印章，连成一线就赢！',
    difficulty: 2,
    stars: '★★',
    memory: '整课复习 · 听力巩固',
    scene: '全家一起玩',
    time: '5-8 分钟',
    kp: '单元复习（一个单元的词）',
    howto: [
      '每人一张 3×3 九宫格，格子填着本单元单词（可家长代填或图片版）',
      '播放单词音频，孩子在对应格子上盖印章',
      '横、竖、斜连成一条线就喊 Bingo！',
      '可以 2 个孩子或亲子对战',
    ],
    tips: '多人游戏，适合周末全家玩；不会写字的用贴纸代替印章。',
    sketch: 'bingo',
  },
]

export function getGame(id) {
  return GAMES.find((g) => g.id === id)
}
